### ISSUE TITLE
Failed to follow README

### ISSUE THREAD

**Issue by mitnk** [rcore-os/zCore#13]
The following error raised on my side:
```
$ make rootfs

wget http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-minirootfs-3.11.3-x86_64.tar.gz -O prebuilt/linux/alpine-minirootfs-3.11.3-x86_64.tar.gz
--2020-05-03 13:27:26--  http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-minirootfs-3.11.3-x86_64.tar.gz
Resolving dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)... 151.101.228.249
Connecting to dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)|151.101.228.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2723602 (2.6M) [application/octet-stream]
Saving to: ‘prebuilt/linux/alpine-minirootfs-3.11.3-x86_64.tar.gz’

prebuilt/linux/alpine-minirootf 100%[======================================================>]   2.60M  29.8KB/s    in 98s

2020-05-03 13:29:06 (27.0 KB/s) - ‘prebuilt/linux/alpine-minirootfs-3.11.3-x86_64.tar.gz’ saved [2723602/2723602]

mkdir -p rootfs
tar xf prebuilt/linux/alpine-minirootfs-3.11.3-x86_64.tar.gz -C rootfs
cp prebuilt/linux/libc-libos.so rootfs/lib/ld-musl-x86_64.so.1

$ cargo run --release -p linux-loader /bin/busybox ls

    Finished release [optimized] target(s) in 0.10s
     Running `target/release/linux-loader /bin/busybox ls`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EINVAL', linux-loader/src/lib.rs:42:23
stack backtrace:
   0:        0x10bd4cc1f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcf90b7e47e11a9ce
   1:        0x10bd6afde - core::fmt::write::h560e714837db4b87
   2:        0x10bd4a537 - std::io::Write::write_fmt::h9d7b0a8de1542891
   3:        0x10bd4f0fa - std::panicking::default_hook::{{closure}}::hf1031e0cc4fa76c4
   4:        0x10bd4ee3c - std::panicking::default_hook::h89dea9edda9793a2
   5:        0x10bd4f6c8 - std::panicking::rust_panic_with_hook::h332622a460c53019
   6:        0x10bd4f292 - rust_begin_unwind
   7:        0x10bd7398f - core::panicking::panic_fmt::hfd0d665e5d65955b
   8:        0x10bd73895 - core::option::expect_none_failed::h7e7ae6bb50cb5378
   9:        0x10bce5a6b - linux_loader::run::ha92fbe9a6a32b970
  10:        0x10bc47080 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h19b465a7654e691b
  11:        0x10bc4e55b - std::thread::local::LocalKey<T>::with::hebd3256d48ffd818
  12:        0x10bc4e420 - std::thread::local::LocalKey<T>::with::he3e228234166e303
  13:        0x10bc45897 - async_std::task::block_on::block_on::h84c8c56dc07f8c25
  14:        0x10bc48305 - linux_loader::main::h7765ce3119d672d2
  15:        0x10bc4d7f6 - std::rt::lang_start::{{closure}}::h8b6d3ed30e178571
  16:        0x10bd4fa29 - std::rt::lang_start_internal::h6bb9eb30b55f695f
  17:        0x10bc48339 - main
```
I followed every step in README. Except I didn't run `git lfs pull` (is this caused by this skip?)
Or is the `busybox ls` a bad case for `busybox [args]`?
Or anything else I'm missing? Thanks.

**Comment by mitnk** [comment]
```
$ cargo run --release -p zircon-loader prebuilt/zircon
   Compiling lazy_static v1.4.0
   ...
   Compiling structopt v0.3.14
   Compiling zircon-loader v0.1.0 (/Users/hugowang/projects/zCore/zircon-loader)
    Finished release [optimized] target(s) in 27.09s
     Running `target/release/zircon-loader prebuilt/zircon`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Did not find ELF magic number"', /Users/hugowang/projects/zCore/zircon-loader/src/lib.rs:64:19
stack backtrace:
   0:        0x103b22faf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcf90b7e47e11a9ce
   1:        0x103b422ce - core::fmt::write::h560e714837db4b87
   2:        0x103b20b57 - std::io::Write::write_fmt::h9d7b0a8de1542891
   3:        0x103b254da - std::panicking::default_hook::{{closure}}::hf1031e0cc4fa76c4
   4:        0x103b2521c - std::panicking::default_hook::h89dea9edda9793a2
   5:        0x103b25aa8 - std::panicking::rust_panic_with_hook::h332622a460c53019
   6:        0x103b25672 - rust_begin_unwind
   7:        0x103b4cd4f - core::panicking::panic_fmt::hfd0d665e5d65955b
   8:        0x103b4cc55 - core::option::expect_none_failed::h7e7ae6bb50cb5378
   9:        0x1039bf67b - zircon_loader::run_userboot::h36f94cc684d03175
  10:        0x1039b0d0c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5da7fa0a2291fef5
  11:        0x1039b5f7b - std::thread::local::LocalKey<T>::with::h5956e45892f658ef
  12:        0x1039b60b0 - std::thread::local::LocalKey<T>::with::hfddf78b52e931649
  13:        0x1039c3c39 - async_std::task::block_on::block_on::he7db9087676c8378
  14:        0x1039b4d5b - zircon_loader::main::h067178259e5f06d5
  15:        0x1039b51f6 - std::rt::lang_start::{{closure}}::h2971b99a4ba0e457
  16:        0x103b25e09 - std::rt::lang_start_internal::h6bb9eb30b55f695f
  17:        0x1039b4d99 - main
```
I'm testing on macOS.

**Comment by jiegec** [comment]
`git lfs pull` is needed.

**Comment by mitnk** [comment]
It works after git lfs pull. Thank you @jiegec
