### ISSUE TITLE
crash in zircon-loader prebuilt/zircon 

### ISSUE THREAD

**Issue by pwq1989** [rcore-os/zCore#70]
backtrace:

```
#0  0x00005652fbc944f8 in ?? ()
#1  0x00007f116fffdad8 in ?? ()
#2  0x00005652fbc944f8 in ?? ()
#3  0x00007f116fffdad8 in ?? ()
#4  0x00005652fac32213 in zircon_loader::spawn::_$u7b$$u7b$closure$u7d$$u7d$::he342d2f69aa4cad0 () at zircon-loader/src/lib.rs:203
#5  0x00005652fac18faa in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hd19fb99a35257388 (
    self=..., cx=0x7f116fffdad8)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:73
#6  0x00005652fac46db0 in _$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h20197d79cea892b8 (self=..., 
    cx=0x7f116fffdad8)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/future.rs:118
#7  0x00005652fac3c60b in _$LT$async_std..task..builder..SupportTaskLocals$LT$F$GT$$u20$as$u20$core..future..future..Future$GT$::poll::_$u7b$$u7b$closure$u7d$$u7d$::h57f15227947c3ec8 () at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/builder.rs:198
#8  0x00005652fac3c467 in async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::_$u7b$$u7b$closure$u7d$$u7d$::hfcf3da47117932b4 (
    current=0x7f116ffff560)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/task_locals_wrapper.rs:60
#9  0x00005652fac4ec39 in std::thread::local::LocalKey$LT$T$GT$::try_with::h75917380ffa184d8 (self=0x5652fb460368, f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
#10 0x00005652fac4e7ae in std::thread::local::LocalKey$LT$T$GT$::with::h48862ae325a7147a (self=0x5652fb460368, f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
#11 0x00005652fac3c3b9 in async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::hf0c989863d035b2d (task=0x5652fbc92288, f=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/task_locals_wrapper.rs:55
#12 0x00005652fac3c5ba in _$LT$async_std..task..builder..SupportTaskLocals$LT$F$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h08f326c2a439b5da (self=..., cx=0x7f116fffdad8) at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/builder.rs:196
#13 0x00005652fac4a377 in async_task::raw::RawTask$LT$F$C$R$C$S$C$T$GT$::run::he018ee4cfb308364 (ptr=0x5652fbc92260)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-3.0.0/src/raw.rs:502
#14 0x00005652facc1eca in async_task::task::Task$LT$T$GT$::run::h90b4213390fc70d6 (self=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-3.0.0/src/task.rs:265
#15 0x00005652faced88f in smol::executor::Worker::tick::_$u7b$$u7b$closure$u7d$$u7d$::h67a5fcfea21df4dd ()
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/executor.rs:323
#16 0x00005652facdef82 in scoped_tls::ScopedKey$LT$T$GT$::set::h71e51edd61554623 (self=0x5652fb4627c0 <smol::executor::WORKER::h435a7c8b7836aecd>, 
    t=0x7f116fffe0f8, f=...) at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
#17 0x00005652facecbef in smol::executor::Worker::enter::h7c880690d3c1e448 (self=0x7f116fffe0f8, f=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/executor.rs:247
#18 0x00005652faced527 in smol::executor::Worker::tick::hc4e2ff00e551ef83 (self=0x7f116fffe0f8)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/executor.rs:323
#19 0x00005652facb0a47 in smol::run::run::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2e3bccffcd1c7bd8 ()
---Type <return> to continue, or q <return> to quit---
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/run.rs:125
#20 0x00005652facb0f32 in scoped_tls::ScopedKey$LT$T$GT$::set::h31aba5750b1882a2 (self=0x5652fb4621a8 <smol::run::WORKER::habac79db926e5901>, 
    t=0x7f116fffe0f8, f=...) at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
#21 0x00005652facb092f in smol::run::run::_$u7b$$u7b$closure$u7d$$u7d$::h0d6298fb1c3da69f ()
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/run.rs:117
#22 0x00005652faca4b72 in smol::context::enter::h09c546b0e8f0c949 (f=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/context.rs:8
#23 0x00005652facb07ab in smol::run::run::ha9451183233ef2a5 (future=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.14/src/run.rs:116
#24 0x00005652faca32fc in async_std::task::builder::Builder::blocking::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6dc40f254d8f5c6a
    () at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/builder.rs:170
#25 0x00005652faca6e41 in async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::_$u7b$$u7b$closure$u7d$$u7d$::h502bc8377ba09697 (
    current=0x7f116ffff560)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/task_locals_wrapper.rs:60
#26 0x00005652faca7c25 in std::thread::local::LocalKey$LT$T$GT$::try_with::h9e867984129b2fbe (self=0x5652fb461520, f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
#27 0x00005652faca72f8 in std::thread::local::LocalKey$LT$T$GT$::with::h1f48bf17a9894c9f (self=0x5652fb461520, f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
#28 0x00005652faca6ce0 in async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h23a496cbab4d2954 (task=0x7f116fffe600, f=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/task_locals_wrapper.rs:55
#29 0x00005652faca346d in async_std::task::builder::Builder::blocking::_$u7b$$u7b$closure$u7d$$u7d$::h910e2c67874e7999 (
    num_nested_blocking=0x7f116ffff548)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/builder.rs:167
#30 0x00005652faca7aba in std::thread::local::LocalKey$LT$T$GT$::try_with::h69a319a162f761da (self=0x5652fb4614e0, f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
#31 0x00005652faca7438 in std::thread::local::LocalKey$LT$T$GT$::with::h8cb9b5441cafc27f (self=0x5652fb4614e0, f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
#32 0x00005652faca320e in async_std::task::builder::Builder::blocking::h39d23b1ca319a5c3 (self=..., future=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/builder.rs:160
#33 0x00005652faca9db5 in async_std::task::block_on::block_on::h105fa08647c926c1 (future=...)
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/block_on.rs:33
#34 0x00005652facae361 in async_std::rt::RUNTIME::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h1b721dc05fa3985e ()
    at /home/odin/peiwenqian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/rt/mod.rs:30
#35 0x00005652facb1206 in std::sys_common::backtrace::__rust_begin_short_backtrace::h49aa8ec852b91e49 (f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
#36 0x00005652facac287 in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h8bbc5a447cf10255 ()
---Type <return> to continue, or q <return> to quit---
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
#37 0x00005652faca656a in _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h3ebb93db4fa79643 (self=..., _args=0)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
#38 0x00005652facac38e in std::panicking::try::do_call::h9f3de9e6f2651f3d (data=0x7f116fffe9f8 "\220\240\300\373RV")
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:297
#39 0x00005652facae69d in __rust_try ()
#40 0x00005652facac304 in std::panicking::try::he0dfd6c8917a7cf6 (f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
#41 0x00005652faca65ea in std::panic::catch_unwind::hde145c3cc2159383 (f=...)
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
#42 0x00005652facac0dd in std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::h8218c71b94901bfd ()
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
#43 0x00005652faca8829 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h2ff01c90b8134d96 ()
    at /home/odin/peiwenqian/.rustup/toolchains/nightly-2020-06-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
#44 0x00005652fb0421ea in call_once<(),FnOnce<()>> () at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/liballoc/boxed.rs:1076
#45 call_once<(),alloc::boxed::Box<FnOnce<()>>> () at /rustc/56daaf669ebc3d5083db5cded719f780dc31104e/src/liballoc/boxed.rs:1076
#46 std::sys::unix::thread::Thread::new::thread_start::hff71cfc60258a5d2 () at src/libstd/sys/unix/thread.rs:87
#47 0x00007f117518ddd5 in start_thread () from /lib64/libpthread.so.0
#48 0x00007f1174ca0ead in clone () from /lib64/libc.so.6

```

command:

```
$ cargo run -p zircon-loader prebuilt/zircon  
   Compiling kernel-hal v0.1.0 (/home/odin/peiwenqian/rust/zCore/kernel-hal)
   Compiling zircon-object v0.1.0 (/home/odin/peiwenqian/rust/zCore/zircon-object)
   Compiling kernel-hal-unix v0.1.0 (/home/odin/peiwenqian/rust/zCore/kernel-hal-unix)
   Compiling zircon-syscall v0.1.0 (/home/odin/peiwenqian/rust/zCore/zircon-syscall)
   Compiling zircon-loader v0.1.0 (/home/odin/peiwenqian/rust/zCore/zircon-loader)
    Finished dev [unoptimized + debuginfo] target(s) in 4.85s
     Running `target/debug/zircon-loader prebuilt/zircon`
userboot: decompressed BOOTFS to VMO!
userboot: searching bootfs for 'bin/bootsvc'
userboot: 'bin/bootsvc' has PT_INTERP "lib/ld.so.1"
userboot: searching bootfs for 'lib/ld.so.1'
userboot: userboot: loaded lib/ld.so.1 at 0x28200000000, entry point 0x282000575cc
userboot: userboot: loaded vDSO at 0x282000ad000, entry point 0x282000b4e6b
userboot: process bin/bootsvc started.
userboot: waiting for loader-service requests...
userboot: searching bootfs for 'lib/liblaunchpad.so'
userboot: searching bootfs for 'lib/libfdio.so'
userboot: searching bootfs for 'lib/libtrace-engine.so'
userboot: searching bootfs for 'lib/libasync-default.so'
userboot: searching bootfs for 'lib/libmemfs.so'
userboot: searching bootfs for 'lib/libc++.so.2'
userboot: searching bootfs for 'lib/libc++abi.so.1'
userboot: searching bootfs for 'lib/libunwind.so.1'
{{{reset}}}
{{{module:0:<application>:elf:dbd5f97ed489b42b}}}
{{{mmap:0x20200000000:0x30000:load:0:r:0}}}
{{{mmap:0x20200030000:0xfd000:load:0:rx:0x30000}}}
{{{mmap:0x2020012d000:0xf000:load:0:rw:0x12d000}}}
{{{mmap:0x2020013c000:0x1000:load:0:rw:0x13c000}}}
dso: id=dbd5f97ed489b42b base=0x0000020200000000 name=<application>
{{{module:0x3:liblaunchpad.so:elf:b76f0d8110442057}}}
{{{mmap:0x282000f6000:0x3000:load:0x3:r:0}}}
{{{mmap:0x282000f9000:0x4000:load:0x3:rx:0x3000}}}
{{{mmap:0x282000fd000:0x1000:load:0x3:rw:0x7000}}}
{{{mmap:0x282000fe000:0x1000:load:0x3:rw:0x8000}}}
dso: id=b76f0d8110442057 base=0x00000282000f6000 name=liblaunchpad.so
{{{module:0x2:<vDSO>:elf:10d74791a14f7360}}}
{{{mmap:0x282000ad000:0x7000:load:0x2:r:0}}}
{{{mmap:0x282000b4000:0x2000:load:0x2:rx:0x7000}}}
dso: id=10d74791a14f7360 base=0x00000282000ad000 name=<vDSO>
{{{module:0x4:libfdio.so:elf:c3bf7a8a244e7287}}}
{{{mmap:0x282000ff000:0x12000:load:0x4:r:0}}}
{{{mmap:0x28200111000:0x3c000:load:0x4:rx:0x12000}}}
{{{mmap:0x2820014d000:0x7000:load:0x4:rw:0x4e000}}}
{{{mmap:0x28200154000:0x4000:load:0x4:rw:0x55000}}}
dso: id=c3bf7a8a244e7287 base=0x00000282000ff000 name=libfdio.so
{{{module:0x5:libtrace-engine.so:elf:f0dd4c361cb612f2}}}
{{{mmap:0x28200158000:0x4000:load:0x5:r:0}}}
{{{mmap:0x2820015c000:0x6000:load:0x5:rx:0x4000}}}
{{{mmap:0x28200162000:0x1000:load:0x5:rw:0xa000}}}
{{{mmap:0x28200163000:0x1000:load:0x5:rw:0xb000}}}
dso: id=f0dd4c361cb612f2 base=0x0000028200158000 name=libtrace-engine.so
{{{module:0x6:libasync-default.so:elf:99150f38cfad363e}}}
{{{mmap:0x28200164000:0x1000:load:0x6:r:0}}}
{{{mmap:0x28200165000:0x1000:load:0x6:rx:0x1000}}}
{{{mmap:0x28200166000:0x1000:load:0x6:rw:0x2000}}}
dso: id=99150f38cfad363e base=0x0000028200164000 name=libasync-default.so
{{{module:0x7:libmemfs.so:elf:c78ca7d6f498fbff}}}
{{{mmap:0x28200167000:0xc000:load:0x7:r:0}}}
{{{mmap:0x28200173000:0x2d000:load:0x7:rx:0xc000}}}
{{{mmap:0x282001a0000:0x5000:load:0x7:rw:0x39000}}}
{{{mmap:0x282001a5000:0x1000:load:0x7:rw:0x3e000}}}
dso: id=c78ca7d6f498fbff base=0x0000028200167000 name=libmemfs.so
{{{module:0x8:libc++.so.2:elf:b93b2e97bb80b9ea}}}
{{{mmap:0x282001a6000:0x53000:load:0x8:r:0}}}
{{{mmap:0x282001f9000:0x74000:load:0x8:rx:0x53000}}}
{{{mmap:0x2820026d000:0x6000:load:0x8:rw:0xc7000}}}
{{{mmap:0x28200273000:0x7000:load:0x8:rw:0xcd000}}}
dso: id=b93b2e97bb80b9ea base=0x00000282001a6000 name=libc++.so.2
{{{module:0x9:libc++abi.so.1:elf:50ce8a297362fa00}}}
{{{mmap:0x2820027a000:0x18000:load:0x9:r:0}}}
{{{mmap:0x28200292000:0x1c000:load:0x9:rx:0x18000}}}
{{{mmap:0x282002ae000:0x4000:load:0x9:rw:0x34000}}}
{{{mmap:0x282002b2000:0x1000:load:0x9:rw:0x38000}}}
dso: id=50ce8a297362fa00 base=0x000002820027a000 name=libc++abi.so.1
{{{module:0x1:libc.so:elf:0e81ca5ebfa5379b}}}
{{{mmap:0x28200000000:0x4f000:load:0x1:r:0}}}
{{{mmap:0x2820004f000:0x59000:load:0x1:rx:0x4f000}}}
{{{mmap:0x282000a8000:0x2000:load:0x1:rw:0xa8000}}}
{{{mmap:0x282000aa000:0x3000:load:0x1:rw:0xaa000}}}
dso: id=0e81ca5ebfa5379b base=0x0000028200000000 name=libc.so
{{{module:0xa:libunwind.so.1:elf:b38531532aba8b47}}}
{{{mmap:0x282002b3000:0x4000:load:0xa:r:0}}}
{{{mmap:0x282002b7000:0x6000:load:0xa:rx:0x4000}}}
{{{mmap:0x282002bd000:0x1000:load:0xa:rw:0xa000}}}
{{{mmap:0x282002be000:0x1000:load:0xa:rw:0xb000}}}
dso: id=b38531532aba8b47 base=0x00000282002b3000 name=libunwind.so.1
bootsvc: Starting...
bootsvc: Taking root resource handle...
bootsvc: Creating bootfs service...
bootsvc: Retrieving boot image...
bootsvc: Decommitted BOOTDATA VMO from 0 to 0x4dbb000
bootsvc: Loading boot arguments...
bootsvc: Creating svcfs service...
bootsvc: Loading kernel VMOs...
bootsvc: Creating loader service...
bootsvc: Launching next process...
userboot: loader-service channel peer closed
bootsvc: bootsvc.next = bin/component_manager,fuchsia-boot:///#meta/root.cm,--use-builtin-process-launcher
userboot: finished!
bootsvc: Launched bin/component_manager
[component_manager] INFO: Component manager is starting up...
fshost: watching for exit
driver_manager: launch /boot/bin/svchost (svchost) OK
console.shell: disabled
driver_manager: launch /boot/bin/pwrbtn-monitor (pwrbtn-monitor) OK
driver_manager: launch /boot/bin/miscsvc (miscsvc) OK
Segmentation fault (core dumped)
```

env:

```
$ uname -r
3.10.0-957.el7.x86_64
$ rustc --version
rustc 1.45.0-nightly (56daaf669 2020-06-03)

$ rpm -qa | grep qemu
qemu-img-1.5.3-173.el7_8.3.x86_64
libvirt-daemon-driver-qemu-4.5.0-10.el7.x86_64
ipxe-roms-qemu-20170123-1.git4e85b27.el7_4.1.noarch
qemu-kvm-1.5.3-173.el7_8.3.x86_64
qemu-kvm-common-1.5.3-173.el7_8.3.x86_64
```

zCore version
```
master branch
42bd799d97ebc10355582cb852837ca29b2fbcf5
```

**Comment by wangrunji0408** [comment]
Thanks for your report. 
This is a known issue same as #52 .
Don't know why now.

**Comment by pwq1989** [comment]
thx

**Comment by chyyuu** [comment]
Using "cargo run  -p zircon-loader prebuilt/zircon" method to run zcore,  zcore is running in user-mode of Linux. I think the REAL problem is there are no simulated device(like qemu) in user-mode zcore.

**Comment by chyyuu** [comment]
The old version of zCore in user mode can run in linux. Please try
```
cd zCore; git check e0ea3b01f92a ;  cargo run --release -p zircon-loader prebuilt/zircon
```
commit e0ea3b01f92a10180a2868d19d50ca632f8bc953
Author: Runji Wang <wangrunji0408@163.com>
Date:   Sun Apr 19 01:41:18 2020 +0800

    fix serial_read on hal-unix. now shell is working on zircon libos on Linux!

@pwq1989  If you have some free time,  please find the bug in current zCore.

**Comment by pwq1989** [comment]
sorry for later reply ..

i try @chyyuu comment but also crashed

```

bootsvc: Starting...
bootsvc: Taking root resource handle...
bootsvc: Creating bootfs service...
bootsvc: Retrieving boot image...
bootsvc: Decommitted BOOTDATA VMO from 0 to 0x4dbb000
bootsvc: Loading boot arguments...
bootsvc: Creating svcfs service...
bootsvc: Loading kernel VMOs...
bootsvc: Creating loader service...
bootsvc: Launching next process...
bootsvc: bootsvc.next = bin/component_manager,fuchsia-boot:///#meta/root.cm,--use-builtin-process-launcher
userboot: loader-service channel peer closed
userboot: finished!
bootsvc: Launched bin/component_manager
[component_manager] INFO: Component manager is starting up...
fshost: watching for exit
driver_manager: launch /boot/bin/svchost (svchost) OK
console.shell: enabled
driver_manager: launch /boot/bin/pwrbtn-monitor (pwrbtn-monitor) OK
Segmentation fault (core dumped)
```
git version
```
$ git status
# HEAD detached at e0ea3b0
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   rboot (new commits)
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       core.25947
no changes added to commit (use "git add" and/or "git commit -a")
```

but backtrace has some different

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `target/release/zircon-loader prebuilt/zircon'.
Program terminated with signal 11, Segmentation fault.
#0  0x000056428f4bd2a0 in ?? ()
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-39.el7.x86_64
(gdb) bt
#0  0x000056428f4bd2a0 in ?? ()
#1  0x00007f4ea39fb5b0 in ?? ()
#2  0x000056428da8c392 in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h8b48337ca2fb3c6c
    ()
#3  0x0000000000000017 in ?? ()
#4  0x0000000000000000 in ?? ()
```

recently i'm not really depth understand zcore design and details, i will try to learn it and found why crashed ...

btw, how can i debug this core or debug codes in guest ...  T_T

**Comment by pwq1989** [comment]
Wow, i found the reason.. so stupid... i should run this in root

use 
```
sudo -E env PATH=$PATH cargo run --release -p zircon-loader prebuilt/zircon
```

this will be ok :)
